In [7]:
import numpy as np
print('list matriks 37')
matriks_a_37 = np.array([[1,2,3,4,5]]) 
print(matriks_a_37)
matriks_b_37 = np.array([[2,3,5,7,11],[4,5,6,7,8]])
print(matriks_b_37)
matriks_c_37 = np.array([[[[1,4,7,8,10],[2,4,5,7,8],[3,6,5,4,9]]]])
print(matriks_c_37)

list matriks 37
[[1 2 3 4 5]]
[[ 2  3  5  7 11]
 [ 4  5  6  7  8]]
[[[[ 1  4  7  8 10]
   [ 2  4  5  7  8]
   [ 3  6  5  4  9]]]]


In [5]:
matriks_a_37.ndim

2

In [9]:
matriks_x_37= np.array ([[2,3,5,7,11],[4,5,6,7,8]])
print(matriks_x_37)


[[ 2  3  5  7 11]
 [ 4  5  6  7  8]]


In [11]:
matriks_a_37 = np.ones ((3,3))
print(matriks_a_37)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
matriks_b_37 = np.zeros ((7,8))
print(matriks_b_37)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
print('matriks identitas')
matriks_c_37 = np.identity ((5))
print(matriks_c_37)

matriks identitas
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
matriks_x_37 = np.identity(7)* 6
matriks_y_37 = np.ones((7,7))
matriks_z_37 = matriks_x_37 * matriks_y_37
print(matriks_z_37)

[[6. 0. 0. 0. 0. 0. 0.]
 [0. 6. 0. 0. 0. 0. 0.]
 [0. 0. 6. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 6. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 0. 0. 6.]]


In [32]:
matriks_x_37 = np.identity(7)* 3
print(matriks_x_37)
matriks_y_37 = np.ones((7,7))
print(matriks_y_37)
matriks_w_37 = np.full((7,7),9)
print(matriks_w_37)
matriks_z_37 = matriks_x_37 + matriks_y_37 - matriks_w_37
print(matriks_z_37)
matriks_z_37[1,1]= -1
matriks_z_37[2,3] = -3
matriks_z_37[3,6] = -12
matriks_z_37[5,2] = -17
matriks_z_37[4,3] = -14
matriks_z_37[6,0] = -22
matriks_z_37[3,0] = -9
print('Matriks z 37=')
print(matriks_z_37)

[[3. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 3.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]
[[-5. -8. -8. -8. -8. -8. -8.]
 [-8. -5. -8. -8. -8. -8. -8.]
 [-8. -8. -5. -8. -8. -8. -8.]
 [-8. -8. -8. -5. -8. -8. -8.]
 [-8. -8. -8. -8. -5. -8. -8.]
 [-8. -8. -8. -8. -8. -5. -8.]
 [-8. -8. -8. -8. -8. -8. -5.]]
Matriks z 37=
[[ -5.  -8.  -8.  -8.  -8.  -8.  -8.]
 [ -8.  -1.  -8.  -8.  -8.  -8.  -8.]
 [ -8.  -8.  -5.  -3.  -8.  -8.  -8.]
 [ -9.  -8.  -8.  -5.  -8.  -8. -12.]
 [ -8.  -8.  -8. -14.  -5.  -8.  -8.]
 [ -8.  -8. -17.  -8.  -8.  -5.  -8.]
 [-22.  -8.  -8.  -8.  -8.  -8.  -5.]]


In [35]:
matriks_x_37 = np.identity(7)* 3
print(matriks_x_37)
matriks_y_37 = np.ones((7,7))
print(matriks_y_37)
matriks_w_37 = np.full((7,7),9) + 2
print(matriks_w_37)
matriks_z_37 = matriks_x_37 + matriks_y_37 * matriks_w_37 
print(matriks_z_37)
matriks_z_37[4,6] = 4
matriks_z_37[0,0] = 1
matriks_z_37[3,5] = 8
matriks_z_37[6,6] = 15
matriks_z_37[6,0] = 9
matriks_z_37[1,4] = 2
matriks_z_37[2,6] = 19
matriks_z_37[4,3] = 28
matriks_z_37[3,0] = 36
print('Matriks z 37=')
print(matriks_z_37)

[[3. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 0. 3.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]]
[[14. 11. 11. 11. 11. 11. 11.]
 [11. 14. 11. 11. 11. 11. 11.]
 [11. 11. 14. 11. 11. 11. 11.]
 [11. 11. 11. 14. 11. 11. 11.]
 [11. 11. 11. 11. 14. 11. 11.]
 [11. 11. 11. 11. 11. 14. 11.]
 [11. 11. 11. 11. 11. 11. 14.]]
Matriks z 37=
[[ 1. 11. 11. 11. 11. 11. 11.]
 [11. 14. 11. 11.  2. 11. 11.]
 [11. 11. 14. 11. 11. 11. 19.]
 [36. 11. 11. 14. 11.  8. 11.]
 [11. 11. 11. 28. 14. 11.  4.]
 [11. 11. 11. 11. 11. 14. 11.]
 [ 9. 11. 11. 11. 11. 11. 15.]]


In [36]:
print('matriks 37=')
np.full((3,4),87)


matriks 37=


array([[87, 87, 87, 87],
       [87, 87, 87, 87],
       [87, 87, 87, 87]])

In [15]:
import numpy as np
matriks_a_37 = np.array([[10,12,11,15],
             [16,12,6,8],
             [13,6,19,10]])
print('Matriks a 37')
print(matriks_a_37)
matriks_x_37 = np.min(matriks_a_37)
print('Nilai minimum matriks a 37')
print(matriks_x_37)
matriks_y_37 = np.max(matriks_a_37)
print('Nilai maximum matriks a 37')
print(matriks_y_37)

Matriks a 37
[[10 12 11 15]
 [16 12  6  8]
 [13  6 19 10]]
Nilai minimum matriks a 37
6
Nilai maximum matriks a 37
19


In [19]:
import numpy as np
matriks_a_37 = np.array([[10,12,11,15],
             [16,12,6,8],
             [13,6,19,10]])
matriks_b_37 = np.array([[20,17,11,5],
             [6,19,3,8],
             [4,13,9,10]])
print('Matriks a 37')
print(matriks_a_37)
print('Matriks b 37')
print(matriks_b_37)
matriks_c_37 = np.sum(matriks_a_37 + matriks_b_37)
print('sum matriks a 37 + sum matriks b 37=')
print(matriks_c_37)

Matriks a 37
[[10 12 11 15]
 [16 12  6  8]
 [13  6 19 10]]
Matriks b 37
[[20 17 11  5]
 [ 6 19  3  8]
 [ 4 13  9 10]]
sum matriks a 37 + sum matriks b 37=
263
